FROM python:3.10
LABEL org.opencontainers.image.authors="cmsj@tenshu.net"
WORKDIR /app
VOLUME [ "/config" ]

COPY . /app
RUN cd /app ; pip3 install . ; cd -
#RUN rm -rf /app

CMD [ "dreambot_frontend_irc.py", "/config/config.json" ]